#!/data/data/com.termux/files/usr/bin/bash
PATH=/data/data/com.termux/files/usr/bin:$PATH
S="$(python3 ~/battlecats-mods/zygisk-bc-poc/bc_log_viewer.py list_patches 2>&1)"
echo "$S" | termux-clipboard-set
echo "$S" | head -5 | termux-toast -g top
