#!/usr/bin/env bash
# Build determinístico da fixture dll2patch. Regenera as .dll de teste.
# Uso: bash test/fixtures/dll2patch/build.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
cd "${SCRIPT_DIR}/src"

rm -rf bin obj

# Compila com determinismo total
dotnet build -c Release -p:Deterministic=true -p:ContinuousIntegrationBuild=true --nologo -v quiet
cp bin/Release/net6.0/dll2patch_fixture.dll "${SCRIPT_DIR}/../dll2patch_fixture.dll"

dotnet run -c Release --project "${SCRIPT_DIR}/facts/Facts.csproj" -- \
    "${SCRIPT_DIR}/../dll2patch_fixture.dll" "${SCRIPT_DIR}"

python3 - "${SCRIPT_DIR}/opcodes_table.csv" \
    "${REPO_ROOT}/manager/src/io/github/rianprei/bepinex/manager/core/Ecma335OpCodes.java" <<'PY'
import csv
import sys

source, destination = sys.argv[1:]
rows = []
with open(source, newline="", encoding="utf-8") as stream:
    for row in csv.DictReader(stream):
        rows.append((int(row["Value"], 16), row["Name"], row["OperandType"], int(row["Size"])))
rows.sort(key=lambda item: (item[0], item[1]))
with open(destination, "w", encoding="utf-8", newline="\n") as output:
    output.write("package io.github.rianprei.bepinex.manager.core;\n\n")
    output.write("// Generated by test/fixtures/dll2patch/build.sh from OpCodes.\n")
    output.write("final class Ecma335OpCodes {\n")
    output.write("    record OpCode(String name, String operandType, int size) {}\n")
    output.write("    static final OpCode[] TABLE = new OpCode[65536];\n")
    output.write("    static {\n")
    last = None
    for value, name, operand_type, size in rows:
        if value == last:
            continue
        last = value
        output.write(
            f'        TABLE[0x{value:04X}] = new OpCode("{name}", "{operand_type}", {size});\n'
        )
    output.write("    }\n")
    output.write("    private Ecma335OpCodes() {}\n")
    output.write("}\n")
PY

echo "DLL, PEReader facts e opcodes gerados em ${SCRIPT_DIR}"
